apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headscale.creco.dev`)
      kind: Rule
      services:
        - name: headscale
          port: 80
  tls:
    secretName: headscale-tls
