apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: private
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      traefik-private-private-allow-internal@kubernetescrd,
      traefik-private-private-errors@kubernetescrd
spec:
  controller: traefik.io/ingress-controller
