replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# 외부 도메인 (본인 도메인으로 변경)
host: hello.creco.dev

# cert-manager ClusterIssuer 이름
clusterIssuer: letsencrypt-prod

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

